### ISSUE TITLE
"attempt to index a nil value" when modifying a file opened through the agenda view.

### ISSUE THREAD

**Issue by HendrikPetertje** [nvim-orgmode/orgmode#115] opened 2021-10-27 08:50 UTC
### Are you using "tree-sitter" branch?

Yes

### Describe the bug

When opening an org-buffer from the calendar view, org-specific commands raise lua errors (file nil) while running the same command in a new buffer loading that file without the calendar raises no issues at all.

### Steps to reproduce

- open nvim and have some org-mode files setup (with dates so they are picked up by the calendar view
- `<leader>oa` follwed by `a` for agenda.
- `<ENTER>` or `<TAB>` into an agenda item
- Try to modify date using `cid`, or forward state of todo using `cit` or perform any other actions that would require lua to parse the todo under the cursor
- Receive `orgmode/parsers/files.lua:208: attempt to index a nil value` 

Close NVIM (or close the .org buffer) and reopen vim and open the same .org file again (directly without the agenda) all commands now work.

In both cases the `?` command still works, it seems to only affect situations where the lua plugin needs to scan/read the file.

### Expected behavior

I would expect to be able to make changes to my org files when I open them from the calendar view. 

### Screenshots and recordings

[Demo](https://filedump.hendrikpeter.net/random/orgmode-problem.mov)

(I open an event using ENTER and then perform `cid` on the date object followed by `cit` on the TODO object)
I close nvim

I re-open nvim, go straight to the file and execute the same tasks.

### OS / Distro

Mac OSX - Big Sur 11.6

### Neovim version/commit

NVIM v0.6.0-dev+496-gc5525f265

### Additional context

Build type: Release
LuaJIT 2.1.0-beta3

**Comment by HendrikPetertje** [comment] 2021-11-01 18:53
So sorry, been super busy with other issues for a few days, I'll try your stuff tomorrow!

**Comment by HendrikPetertje** [comment] 2021-11-01 19:18
I just fixed the titles on my items, nice catch!.

When I open an item from the calendar and then try to manipulate dates or forward the state (or any other action that would affect the file) I still get thrown in to an error situation

`:e!` doesn't fix that sadly, closing the buffer entirely and then re-opening it with `:e filename` does work!

The vim config I'm doing this with is:
https://git.hendrikpeter.net/hendrikpeter/pico-vim

I tried your Gist with minimal lua, but opening org files using that config results in this:
![image](https://user-images.githubusercontent.com/3583395/139728389-9050da5e-d9a2-4404-b76e-c683fd27e165.png)

I'll poke around a bit, turn settings off and on and see what happens!

**Comment by HendrikPetertje** [comment] 2021-11-01 19:21
side-detail:
there is another case where the nil error can happen from time to time that is irrelevant to this specific bug (I think, but probably the problem @levouh is running into):

1. Open a file with org stuff, dates and todos
2. Insert a new line somewhere
3. attempt to change date, state or other information on a todo item (below the new newline)
4. Same nil failure as OP.
5. save file
6. attempt to change date, state or other info again: great success!

I don't really see that as a bug though; i can just save the file after adding new stuff.

**Comment by HendrikPetertje** [comment] 2021-11-01 19:26
While restoring nvim back to my own config I performed a PlugUpdate followed by :TSUpdate to get everything back to what it should be and upgrade stuff while I'm at it

and the problem in OP is gone now.

**Comment by kristijanhusak** [comment] 2021-11-01 21:00
@HendrikPetertje awesome, thanks. I'll leave it open for now in case someone finds any similar issues or if @levouh manages to reproduce it.

**Comment by kristijanhusak** [comment] 2021-12-06 15:51
Closing this since it's been a while since someone reported anything, and now with 0.6.0 out we have proper diagnostics api. There are still some parsing issues that I hope will be resolved once tree-sitter grammar gets 1.0.0 release. If something strange pops up let me know.

**Closed by kristijanhusak** 2021-12-06 15:51 UTC
Labels: bug
