### ISSUE TITLE
Category Inheritance

### ISSUE THREAD

**Issue by pureume** [nvim-orgmode/orgmode#296] opened 2022-05-19 14:21 UTC
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

Relevant Org Manual links:

* [Property Inheritance](https://orgmode.org/manual/Property-Inheritance.html#Property-Inheritance)
* [Categories](https://orgmode.org/manual/Categories.html#Categories)

### Additional context

In Emacs, setting categories per-file or per-subtree is a useful feature that allows some flexibility in how you organize your agenda (although it is disabled by default). Currently categories are reflected in the agenda of nvim-orgmode, but they must be declared for each and every item. It would be nice to have the option to set the category for a whole file (which is helpful when the actual filename is not very agenda friendly) or to set the category for entire sub-trees to eliminate a lot of redundant property drawers. 

I have been using tags to achieve this, but the category name occupies some special real estate in the agenda which would be nice to utilize meaningfully.

Also, thanks again for this great plugin! :)

**Comment by kristijanhusak** [comment] 2022-05-24 18:50
I just pushed a fix for the file level category. There was support for that initially (even before tree-sitter), but it got lost in the refactoring. Subtree is partially working. If you define a property on a single headline, agenda will pick it up, but it will not cascade down to the children.

**Comment by pureume** [comment] 2022-05-25 03:09
Just tested out the file-level category definition, and it indeed works. Thank you for that :)

**Comment by kristijanhusak** [comment] 2022-05-25 09:23
> I noticed, however, that the file-level category overrides the individually set categories of individual headlines.

I can't reproduce this. Can you give me an example org file?

**Comment by pureume** [comment] 2022-05-25 13:35
Sorry, I was mistaken. I had forgotten that children do not yet inherit the categories of their parents.

**Comment by kristijanhusak** [comment] 2022-05-26 20:28
Inheritance should be working now. Let me know if it's still broken.

**Closed** 2022-05-26 20:28 UTC
Labels: enhancement
