### ISSUE TITLE
Scheduled tasks with repeater don't show on agenda when overdue

### ISSUE THREAD

**Issue by omar-nelson-hernandez** [nvim-orgmode/orgmode#372] opened 2022-07-21 22:29 UTC
### Describe the bug

Whenever you have a scheduled task with a repeater like:

```
* TODO Pay CC test
  SCHEDULED: <2022-06-14 Tue ++1m>

  some test
```
and the scheduled date is in the past, the reminder only appears in the agenda on the given scheduled date, if the task is not completed it won't appear in future days in the agenda, like it used to do.

### Steps to reproduce

A single scheduled task, with a schedule date in the past and a repeater (around a month, for some reason it works as expected with short repeaters like ++1h or ++3d but not ++1m), like:

```
* TODO Pay CC test
  SCHEDULED: <2022-06-14 Tue ++1m>

  some test
```
Opening the agenda will show something like this:

```
Thursday   14 July 2022
  art:        Scheduled: TODO drawabox.com
  test:       Scheduled: TODO Pay CC test
Friday     15 July 2022
  art:        Scheduled: TODO drawabox.com
Saturday   16 July 2022
  art:        Scheduled: TODO drawabox.com
```
No reminders after the item is overdue, only on the due date.

Strangely the issue doesn't happen with shorter repeaters, like:

```
* TODO Pay CC test
  SCHEDULED: <2022-06-14 Tue ++1h>

  some test
```
The items are correctly displayed in the agenda:

```
Wednesday  20 July 2022
  art:        Scheduled: TODO drawabox.com
  test:       Scheduled: TODO Pay CC test
Thursday   21 July 2022
  desktop:    16:20...... TODO polybar
  server:     Sched. 96x: TODO [#B] Fix server fan noise
  desktop:    Sched. 44x: TODO polybar
  art:        Scheduled:  TODO drawabox.com
  test:       Scheduled:  TODO Pay CC test
Friday     22 July 2022
  art:        Scheduled: TODO drawabox.com
  test:       Scheduled: TODO Pay CC test
```

### Expected behavior

The TODO item should appear on the agenda every day from the time it became overdue until it is marked as complete (and the due date is updated because of the repeater)

### Emacs functionality

The reminders in the agenda appear there until the item is completed or the due date moved, as per: https://orgmode.org/manual/Repeated-tasks.html

### Minimal init.lua

```
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup({
    {
      'wbthomason/packer.nvim',
      { 'nvim-treesitter/nvim-treesitter' },
      { 'kristijanhusak/orgmode.nvim', branch = 'master' },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  })
end

_G.load_config = function()
  require('orgmode').setup_ts_grammar()
  require('nvim-treesitter.configs').setup({
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { 'org' },
    },
  })

  vim.cmd([[packadd nvim-treesitter]])
  vim.cmd([[runtime plugin/nvim-treesitter.lua]])
  vim.cmd([[TSUpdateSync org]])

  -- Close packer after install
  if vim.bo.filetype == 'packer' then
    vim.api.nvim_win_close(0, true)
  end

  require('orgmode').setup()

  -- Reload current file if it's org file to reload tree-sitter
  if vim.bo.filetype == 'org' then
    vim.cmd([[edit!]])
  end
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path })
  load_plugins()
  require('packer').sync()
  vim.cmd([[autocmd User PackerCompileDone ++once lua load_config()]])
else
  load_plugins()
  load_config()
end

require('orgmode').setup_ts_grammar()

require('orgmode').setup({
  org_agenda_files = '/storage/notebook/org/*',
  org_default_notes_file = '/storage/notebook/org/refile.org',
  org_todo_keywords = {'TODO(t)', 'BLOCKED(b)', '|', 'DONE(d)'},
  org_time_stamp_rounding_minutes = 1,
  org_priority_default = 'C'
})
```

### OS / Distro

Debian 10

### Neovim version/commit

NVIM v0.8.0-dev-nightly-5-g1f1863ed5

**Comment by jgollenz** [comment] 2022-07-21 23:19
I'm not sure that I correctly understand what you mean. When I schedule something on the 16th of July (with a monthly repeater), there exactly two days within the following thirty days on which I would expect that task to appear on the agenda: Today (because the task from July 16th is overdue) and August 16th. That is indeed not what happens on the monthly repeater, but also not on the weekly or the yearly reminder. 

What I'm confused about is your example with the hourly reminder. Actually, I'm not sure what should be displayed on the agenda at all in such a case, because today that task from July 16th will have been scheduled some 120 times, and the one right after it 119 times. Not arguing that it makes much sense to display all the times an hourly repeated task was scheduled, but I'd like to know what the correct way in Emacs org-mode is. Except for the hour case (because it is not scheduled 24 times a day, for GOOD REASON), all other repeaters seem to be consistent in that they only show up on the days that they are actually scheduled

**Comment by omar-nelson-hernandez** [comment] 2022-07-22 14:25
I believe this to be a combination of two features, [deadlines / scheduling](https://orgmode.org/manual/Deadlines-and-Scheduling.html) and [repeated tasks](https://orgmode.org/manual/Repeated-tasks.html).

From what I understand from the documentation on scheduling, when you schedule an item and don't do it on the scheduled date, it will appear on the agenda for today every single day until you do it, this is the relevant section on the docs:

> ‘SCHEDULED’
> 
>     Meaning: you are planning to start working on that task on the given date.
> 
>     The headline is listed under the given date[65](https://orgmode.org/manual/Deadlines-and-Scheduling.html#FOOT65). 
>     In addition, a reminder that the scheduled date has passed is present in the compilation for today, until the entry is marked as done, i.e., the task is automatically forwarded until completed.

This part works fine when you don't use repeaters, like this one, it has been overdue for 97 days:

`  server:     Sched. 97x: TODO [#B] Fix server fan noise`

As soon as you add a repeater, the logic for the schedule breaks and it only notifies you on the day it is scheduled. **The logic from the schedule should not be modified when adding a repeater, you should get a reminder every day until you complete it or move the schedule date**. The repeater is only there to let ORG know that whenever your mark the task as complete, it should just move the date to the future according to the repeater configuration and not mark it as DONE so it still appears in the agenda in the future.

From what I understand, the repeater should only affect the behavior when the task is marked as DONE, it should move the deadline or due date in the future and leave it as a TODO. But currently, using a repeater breaks the scheduling logic.

I have never used emacs org, but I used the documentation to understand how it should work, please let me know if my understanding is incorrect or if you need additional information about this.

PS. This feature used to work as i described it, it was just recently modified, that's why I believe it is an error. I recently updated all my plugins and my neovim version and it stopped working, unfortunately I don't have the hash for the version that used to work.

**Comment by cands** [comment] 2022-07-26 09:30
Yes, I also believe that this is a bug that has been introduced in some recent update, this used to work as in Emacs. I can confirm that the behaviour now differs from Emacs, i.e. in Emacs overdue tasks with repeaters are shown in the agenda after their due date has passed, whereas they are not shown in nvim-orgmode.

For example, I have some tasks repeated weekly and monthly that are shown as overdue in Emacs agenda (marked as "X d. ago:") but are not shown in nvim-orgmode on views that include later dates (the tasks are correctly shown if the chosen view includes the due date).

I think it is important to fix this so that the functionality matches Emacs, otherwise there is a risk that repeated tasks that are overdue are missed since they disappear from the agenda.

**Comment by jgollenz** [comment] 2022-07-26 10:01
@cands could you please test what happens in the agenda if a scheduled task with a repeater "wraps-around"? Let's say we have a task on a Monday with a weekly repeater. If I missed the task last week on Monday, what will be displayed on the agenda on this weeks Tuesday? Is it both `Sched. 9x: TODO task` for last week and `Sched. 2x: TODO task` for this week or only the latter?

Also, do you know how an hourly-repeated scheduled task behaves?

**Comment by cands** [comment] 2022-07-26 11:10
@jgollenz I did a quick test and it shows that in Emacs the task is then shown in today's agenda as ` 9 d. ago:` only (it is not shown in nvim-orgmode, only if the agenda view includes the actual due dates). I have not used hourly-repeated tasks, so I don't know their behaviour.

**Comment by kristijanhusak** [comment] 2022-08-02 14:11
This bug was introduced with fix for https://github.com/nvim-orgmode/orgmode/issues/337. I reverted it, should be working fine now.

**Closed** 2022-08-02 14:10 UTC
Labels: bug

**Comment by omar-nelson-hernandez** [comment] 2022-08-02 17:13
Beautiful work, works as expected, thanks everybody involved!
