### ISSUE TITLE
if a link url is file only, open_at_point() action will continue its execution to the end with self:_goto_headline(headline), which will cause an error message

### ISSUE THREAD

**Issue by CaeChao** [nvim-orgmode/orgmode#807] opened 2024-09-05 16:27 UTC
### Describe the bug

![image](https://github.com/user-attachments/assets/05057edb-e871-4ed8-a922-03c3199edeb7)
 Error message: attempt to index field 'file' (a nil value)
I think it is caused by the line 919 in lua/orgmode/org/mappings.lua:
![image](https://github.com/user-attachments/assets/258c42e3-fbb6-4840-b81a-96184c7a57f0)
which the line `vim.cmd([[normal! zv]])` should be executed with a return, so that the function won't continue its execution to line 957 `self:_goto_headline(headline)` when the link is `is_file_only`

### Steps to reproduce

 create a file only link and open it at point

### Expected behavior

should not popup error message 

### Minimal init.lua

```lua

require('lazy').setup({
  {
    'nvim-orgmode/orgmode',
    event = 'VeryLazy',
    ft = { 'org' },
    config = function()
      require('orgmode').setup()
    end,
  },
}, {
  root = lazy_root,
  lockfile = nvim_root .. '/lazy.json',
  install = {
    missing = false,
  },
})
```

### OS / Distro

Linux

### Neovim version/commit

v0.10.0

**Comment by kristijanhusak** [comment] 2024-09-05 20:26
Can you try using this branch and see if it works?

https://github.com/nvim-orgmode/orgmode/pull/803

**Comment by CaeChao** [comment] 2024-09-06 00:43
![image](https://github.com/user-attachments/assets/e72fa170-a045-4732-a813-efbaeea86fce)
The Error message is replaced with a warning message

**Comment by kristijanhusak** [comment] 2024-09-06 06:47
Please provide exact steps how to reproduce. I'm not able to reproduce it.
I tried these formats and none of them error/warning:

```
* Headline
Non existing file:
[[file:./test_file.org]]
[[./test_file.org]]

Existing file:
[[file:./todos.org]]
[[./todos.org]]
```

**Comment by CaeChao** [comment] 2024-09-06 19:36
### Steps to Reproduce:
test.org:
```
[[./test_file.org][Test file]]
```
![image](https://github.com/user-attachments/assets/39277062-c0c8-4cbb-94a9-c5a3ede7bb8e)
test_file.org:
```


* Headline

** Head 2
```
![image](https://github.com/user-attachments/assets/123aa9d5-55ed-4ae4-a8c0-554554d70ce3)

### Result:
![image](https://github.com/user-attachments/assets/445dd555-a63e-48e6-ac40-6dff1c9be749)

**Comment by CaeChao** [comment] 2024-09-06 19:41
After I added a return before the vim.cmd at line 919 lua/orgmode/org/mappings.lua in master branch
![image](https://github.com/user-attachments/assets/68491b39-9d72-46dc-8d3f-e2bf14733be7)
 none of error/warning appear again

**Comment by kristijanhusak** [comment] 2024-09-16 16:36
Since https://github.com/nvim-orgmode/orgmode/pull/803 will be merged fairly soon, I fixed the issue there.

**Comment by kristijanhusak** [comment] 2024-09-18 10:31
PR https://github.com/nvim-orgmode/orgmode/pull/803 is merged, so I'm considering this issue solved. If you run into anything let me know.

**Closed by kristijanhusak** 2024-09-18 10:31 UTC
Labels: bug
