### ISSUE TITLE
backslash in text creates error condition

### ISSUE THREAD

**Issue by hakling** [nvim-orgmode/orgmode#157] opened 2021-11-19 17:07 UTC
### Describe the bug

Text which includes a backslashed punctuation character creates an error conditions. e.g. \. \[, etc.

### Steps to reproduce

1. enter any line with text such as "this [word]" - no problem
2. put  a backslash in front of [ or .
3. results in "Error on text "This \[word]"  

### Expected behavior

Just display the backslashed character. 

### Emacs functionality

Backslashed text is displayed properly, No error is raised.

### Minimal init.lua

No changes made to default initl.lua

### OS / Distro

Ubuntu 21.04    5.11.0-40-generic #44-Ubuntu SMP

### Neovim version/commit

NVIM v0.6.0-dev+575-g2ef9d2a66

### Additional context

This may represent a known limitation, but I've not found it documented anywhere. Issue arose when taking notes on coding.

**Comment by kristijanhusak** [comment] 2021-11-19 17:13
This is coming from treesitter parser. I'll need to check what's happening there.

**Comment by hakling** [comment] 2021-11-19 17:59
Seems the issue may be a bit broader. The following line results in the same error:
'A random line with $ in it'
The issue seems to be the $ surrounded by blanks. If the $ is followed by text it is okay. e.g. $word is treated properly

**Comment by hakling** [comment] 2021-11-20 02:42
And, if the last line in a fold ends in a period, it seems not be included in the fold.

**Comment by kristijanhusak** [comment] 2021-11-20 20:38
> And, if the last line in a fold ends in a period, it seems not be included in the fold.

Can you give an example here? I can't reproduce this. Other things are reproduced.

**Comment by hakling** [comment] 2021-11-20 21:01
I'll try to recreate and let you know, but right now, I can't duplicate it.
I'm trying to convert files that I've been using on emacs and am having
regular weird issues with folding and "Error on text" without it being
clear what the issue is. I've attached a png of what I'm trying to sort out
now.

**Comment by kristijanhusak** [comment] 2021-11-20 21:03
I'm not seing an image, probably because you wrote from in-mail. Make sure to recalculate folds with `zx` before reporting any potential issues, since Vim/Neovim folding can be a bit confused at first.

**Comment by hakling** [comment] 2021-11-21 03:04
One problem I have that is reproducible in the inclusion of a standalone $
in text causes an error to be raised. Some of my org files include text
copied from a terminal session which tend to include such a  naked $. Don't
know if this is a bug, but it is a nuisance. If you like, I'll make that a
bug report.
Most of my other issues have been related to sloppy formatting which
emacs' orgmode seems to handle better.
Thanks.
Hal

**Comment by kristijanhusak** [comment] 2022-04-03 15:56
Theseshould be fixed with the latest master. If the issue persist, let me know and I'll reopen the issue.

**Closed by kristijanhusak** 2022-04-03 15:56 UTC
Labels: bug
